"use client";

import { Suspense, useState, useEffect, useRef, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/header";
import { Search, Play, Loader2, Upload, X, Bell, Settings2 } from "lucide-react";
import type { Product } from "@/types/product";
import type { UserPreferences } from "@/types/preferences";

const PreferenceMannequin = dynamic(
  () =>
    import("@/components/preference-mannequin").then(
      (m) => m.PreferenceMannequin
    ),
  { ssr: false }
);

const STORAGE_KEY = "thread_tryon_job";

interface TryOnJob {
  operationName: string;
  product: Product;
  startedAt: number;
}

export default function OutfitPage() {
  return (
    <Suspense>
      <OutfitPageInner />
    </Suspense>
  );
}

function OutfitPageInner() {
  const searchParams = useSearchParams();
  const [prefs, setPrefs] = useState<UserPreferences | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [generating, setGenerating] = useState(false);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pollMsg, setPollMsg] = useState<string | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const mountedRef = useRef(true);
  const [pendingGenerate, setPendingGenerate] = useState(false);
  const hasAutoGenerated = useRef(false);

  const TRYON_PRODUCT_KEY = "thread_tryon_product";

  // On mount: check for product in sessionStorage (from "Try it on" button)
  useEffect(() => {
    const shouldGenerate = searchParams.get("generate") === "true";
    const stored = sessionStorage.getItem(TRYON_PRODUCT_KEY);
    if (stored && shouldGenerate && !hasAutoGenerated.current) {
      try {
        const product: Product = JSON.parse(stored);
        sessionStorage.removeItem(TRYON_PRODUCT_KEY);
        hasAutoGenerated.current = true;
        setSelectedProduct(product);
        setPendingGenerate(true);
      } catch {
        sessionStorage.removeItem(TRYON_PRODUCT_KEY);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fetch user preferences
  useEffect(() => {
    fetch("/api/preferences")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (data?.preferences) setPrefs(data.preferences);
        else if (data && !data.preferences) setPrefs(data);
      })
      .catch(() => {});
  }, []);

  // Fetch products for selection
  useEffect(() => {
    const params = new URLSearchParams({ limit: "20" });
    if (searchQuery) params.set("category", searchQuery);
    fetch(`/api/products?${params}`)
      .then((r) => r.json())
      .then((data) => setProducts(data.products ?? []))
      .catch(() => {});
  }, [searchQuery]);

  // Request notification permission on mount
  useEffect(() => {
    if ("Notification" in window && Notification.permission === "default") {
      Notification.requestPermission();
    }
  }, []);

  const sendNotification = useCallback((title: string, body: string) => {
    if ("Notification" in window && Notification.permission === "granted") {
      new Notification(title, { body, icon: "/thread-logo.svg" });
    }
  }, []);

  const startPolling = useCallback(
    (opName: string, product: Product) => {
      if (pollRef.current) clearInterval(pollRef.current);

      setGenerating(true);
      setSelectedProduct(product);
      setPollMsg(
        "Generating video — feel free to browse around, we'll notify you when it's ready!"
      );

      let attempts = 0;
      const maxAttempts = 60;

      pollRef.current = setInterval(async () => {
        attempts++;
        if (attempts > maxAttempts) {
          if (pollRef.current) clearInterval(pollRef.current);
          pollRef.current = null;
          sessionStorage.removeItem(STORAGE_KEY);
          if (mountedRef.current) {
            setError("Generation timed out. Please try again.");
            setGenerating(false);
            setPollMsg(null);
          }
          return;
        }

        try {
          const pollRes = await fetch(
            `/api/tryon/video?op=${encodeURIComponent(opName)}`
          );
          const pollData = await pollRes.json();

          if (pollData.error) {
            if (pollRef.current) clearInterval(pollRef.current);
            pollRef.current = null;
            sessionStorage.removeItem(STORAGE_KEY);
            if (mountedRef.current) {
              setError(pollData.error);
              setGenerating(false);
              setPollMsg(null);
            }
            return;
          }

          if (pollData.done && pollData.videoUrl) {
            if (pollRef.current) clearInterval(pollRef.current);
            pollRef.current = null;
            sessionStorage.removeItem(STORAGE_KEY);
            if (mountedRef.current) {
              setVideoUrl(pollData.videoUrl);
              setGenerating(false);
              setPollMsg(null);
            }
            if (document.hidden) {
              sendNotification(
                "Try-on video ready!",
                `Your ${product.name} video is ready to view.`
              );
            }
          }
        } catch {
          // Keep polling on transient errors
        }
      }, 5000);
    },
    [sendNotification]
  );

  // Resume polling from sessionStorage on mount
  useEffect(() => {
    mountedRef.current = true;
    const stored = sessionStorage.getItem(STORAGE_KEY);
    if (stored) {
      try {
        const job: TryOnJob = JSON.parse(stored);
        if (Date.now() - job.startedAt < 5 * 60 * 1000) {
          startPolling(job.operationName, job.product);
        } else {
          sessionStorage.removeItem(STORAGE_KEY);
        }
      } catch {
        sessionStorage.removeItem(STORAGE_KEY);
      }
    }
    return () => {
      mountedRef.current = false;
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, [startPolling]);

  const handleGenerate = useCallback(async (product?: Product) => {
    const p = product ?? selectedProduct;
    if (!p) return;
    setGenerating(true);
    setVideoUrl(null);
    setError(null);
    setPollMsg("Starting generation...");

    try {
      const startRes = await fetch("/api/tryon/video", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productImageUrl: p.image_url,
          productName: p.name,
        }),
      });

      if (!startRes.ok) {
        const data = await startRes.json().catch(() => ({}));
        throw new Error(data.error || "Failed to start generation");
      }

      const { operationName } = await startRes.json();
      if (!operationName) throw new Error("No operation name returned");

      const job: TryOnJob = {
        operationName,
        product: p,
        startedAt: Date.now(),
      };
      sessionStorage.setItem(STORAGE_KEY, JSON.stringify(job));

      startPolling(operationName, p);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Generation failed");
      setGenerating(false);
      setPollMsg(null);
    }
  }, [selectedProduct, startPolling]);

  // Auto-generate: fires once when product is ready and pendingGenerate is set
  useEffect(() => {
    if (pendingGenerate && selectedProduct && !generating && !videoUrl) {
      setPendingGenerate(false);
      handleGenerate(selectedProduct);
    }
  }, [pendingGenerate, selectedProduct, generating, videoUrl, handleGenerate]);

  const heightCm = prefs?.height_cm ?? 170;
  const weightKg = prefs?.weight_kg ?? 70;
  const gender = prefs?.gender ?? "male";
  const fitPref = prefs?.fit_preference ?? "regular";

  return (
    <main className="min-h-screen bg-background">
      <Header />
      <div className="pt-28" />

      <div className="mx-auto max-w-7xl px-6 md:px-12">
        <h1 className="text-4xl font-bold tracking-tight text-foreground md:text-5xl">
          Try On
        </h1>
        <p className="mt-2 text-lg text-muted-foreground">
          See how pieces look with AI-generated video and your 3D body model.
        </p>
      </div>

      {/* ── Bento Grid ── */}
      <div className="mx-auto max-w-7xl px-6 py-8 md:px-12">
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-3 lg:grid-rows-[320px_240px_auto]">

          {/* ── Video / Generation — spans 2 cols, 2 rows ── */}
          <div className="relative rounded-2xl bg-secondary overflow-hidden lg:col-span-2 lg:row-span-2 flex items-center justify-center min-h-[400px] lg:min-h-0">
            {videoUrl ? (
              <div className="flex h-full w-full">
                {/* Product card pinned left */}
                {selectedProduct && (
                  <div className="hidden lg:flex flex-col items-center gap-3 p-5 bg-background/80 backdrop-blur-sm border-r border-border w-48 shrink-0">
                    <div className="relative h-44 w-full rounded-xl overflow-hidden bg-secondary">
                      {selectedProduct.image_url && (
                        <Image
                          src={selectedProduct.image_url}
                          alt={selectedProduct.name}
                          fill
                          className="object-cover"
                          sizes="180px"
                        />
                      )}
                    </div>
                    <div className="text-center">
                      <p className="text-xs font-semibold text-foreground line-clamp-2">
                        {selectedProduct.name}
                      </p>
                      {selectedProduct.brand && (
                        <p className="text-[10px] text-muted-foreground mt-0.5">
                          {selectedProduct.brand}
                        </p>
                      )}
                      {selectedProduct.price != null && (
                        <p className="text-sm font-bold text-foreground mt-1">
                          ${selectedProduct.price.toFixed(2)}
                        </p>
                      )}
                    </div>
                  </div>
                )}
                <video
                  ref={videoRef}
                  src={videoUrl}
                  className="h-full flex-1 object-cover"
                  controls
                  autoPlay
                  loop
                />
              </div>
            ) : generating ? (
              <div className="flex h-full w-full items-center">
                {/* Product card pinned left while generating */}
                {selectedProduct && (
                  <div className="hidden lg:flex flex-col items-center gap-3 p-5 border-r border-border w-48 shrink-0">
                    <div className="relative h-44 w-full rounded-xl overflow-hidden bg-background">
                      {selectedProduct.image_url && (
                        <Image
                          src={selectedProduct.image_url}
                          alt={selectedProduct.name}
                          fill
                          className="object-cover"
                          sizes="180px"
                        />
                      )}
                    </div>
                    <div className="text-center">
                      <p className="text-xs font-semibold text-foreground line-clamp-2">
                        {selectedProduct.name}
                      </p>
                      {selectedProduct.brand && (
                        <p className="text-[10px] text-muted-foreground mt-0.5">
                          {selectedProduct.brand}
                        </p>
                      )}
                      {selectedProduct.price != null && (
                        <p className="text-sm font-bold text-foreground mt-1">
                          ${selectedProduct.price.toFixed(2)}
                        </p>
                      )}
                    </div>
                  </div>
                )}
                <div className="flex flex-1 flex-col items-center gap-4 px-8 text-center">
                  <Loader2
                    size={36}
                    className="animate-spin text-muted-foreground"
                  />
                  <p className="text-sm text-muted-foreground max-w-xs">{pollMsg}</p>
                  <div className="flex items-center gap-2 rounded-full bg-foreground/5 border border-border px-4 py-2">
                    <Bell size={14} className="text-muted-foreground" />
                    <p className="text-xs text-muted-foreground">
                      We&apos;ll notify you when it&apos;s done
                    </p>
                  </div>
                </div>
              </div>
            ) : selectedProduct ? (
              <div className="flex flex-col items-center gap-5">
                <div className="relative h-52 w-40 rounded-xl overflow-hidden bg-background shadow-lg">
                  {selectedProduct.image_url && (
                    <Image
                      src={selectedProduct.image_url}
                      alt={selectedProduct.name}
                      fill
                      className="object-cover"
                      sizes="160px"
                    />
                  )}
                </div>
                <div className="text-center">
                  <p className="text-sm font-semibold text-foreground">
                    {selectedProduct.name}
                  </p>
                  {selectedProduct.price != null && (
                    <p className="text-sm text-muted-foreground">
                      ${selectedProduct.price.toFixed(2)}
                    </p>
                  )}
                </div>
                <button
                  onClick={handleGenerate}
                  className="flex items-center gap-2 rounded-full bg-foreground px-7 py-3 text-sm font-semibold text-background hover:opacity-80 transition-opacity"
                >
                  <Play size={16} />
                  Generate Video
                </button>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-3 text-muted-foreground">
                <Upload size={36} />
                <p className="text-sm">Select a product below to try on</p>
              </div>
            )}

            {error && (
              <div className="absolute bottom-4 left-4 right-4 rounded-xl bg-red-500/10 border border-red-500/20 px-4 py-3 text-sm text-red-400">
                {error}
              </div>
            )}

            {videoUrl && (
              <button
                onClick={() => {
                  setVideoUrl(null);
                  setError(null);
                }}
                className="absolute top-3 right-3 rounded-full bg-black/60 p-2 text-white hover:bg-black/80 transition-colors"
              >
                <X size={16} />
              </button>
            )}
          </div>

          {/* ── Mannequin — top right ── */}
          <div className="relative rounded-2xl bg-secondary overflow-hidden min-h-[320px]">
            <PreferenceMannequin
              heightCm={heightCm}
              weightKg={weightKg}
              gender={gender}
              fitPreference={fitPref}
            />

            {/* Settings overlay */}
            <div className="absolute top-3 left-3 flex flex-col gap-1">
              <div className="rounded-lg bg-black/50 backdrop-blur-md px-3 py-2">
                <div className="grid grid-cols-2 gap-x-4 gap-y-0.5 text-[11px] text-white/80">
                  <span className="text-white/40">Height</span>
                  <span className="font-medium">{heightCm} cm</span>
                  <span className="text-white/40">Weight</span>
                  <span className="font-medium">{weightKg} kg</span>
                </div>
              </div>
              <Link
                href="/preferences"
                className="flex items-center gap-1 rounded-full bg-black/50 backdrop-blur-md px-2.5 py-1 text-[10px] text-white/50 hover:text-white transition-colors w-fit"
              >
                <Settings2 size={10} />
                Edit
              </Link>
            </div>

            {!prefs && (
              <div className="absolute inset-0 flex items-center justify-center bg-black/30 backdrop-blur-sm">
                <a
                  href="/preferences"
                  className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-black hover:bg-white/90 transition-colors"
                >
                  Set up preferences
                </a>
              </div>
            )}
          </div>

          {/* ── Body info card — bottom right ── */}
          <div className="rounded-2xl bg-secondary p-5 flex flex-col justify-between">
            <div>
              <p className="text-[10px] font-medium uppercase tracking-widest text-muted-foreground">
                Body Model
              </p>
              <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-2">
                <div>
                  <p className="text-2xl font-bold text-foreground">{heightCm}</p>
                  <p className="text-[11px] text-muted-foreground">cm tall</p>
                </div>
                <div>
                  <p className="text-2xl font-bold text-foreground">{weightKg}</p>
                  <p className="text-[11px] text-muted-foreground">kg</p>
                </div>
                <div>
                  <p className="text-sm font-semibold text-foreground capitalize">{gender}</p>
                  <p className="text-[11px] text-muted-foreground">gender</p>
                </div>
                <div>
                  <p className="text-sm font-semibold text-foreground capitalize">{fitPref}</p>
                  <p className="text-[11px] text-muted-foreground">fit</p>
                </div>
              </div>
            </div>
            <Link
              href="/preferences"
              className="mt-4 flex items-center justify-center gap-1.5 rounded-full border border-border py-2 text-xs font-medium text-muted-foreground hover:text-foreground hover:border-foreground/30 transition-colors"
            >
              <Settings2 size={12} />
              Edit preferences
            </Link>
          </div>

          {/* ── Product picker — full width bottom ── */}
          <div className="rounded-2xl border border-border bg-background p-4 lg:col-span-3">
            <div className="relative mb-3">
              <Search
                size={16}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
              />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Filter by category..."
                className="w-full rounded-full border border-border bg-secondary pl-9 pr-4 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-foreground/30"
              />
            </div>
            <div className="flex gap-3 overflow-x-auto pb-1 scrollbar-hide">
              {products.map((p) => (
                <button
                  key={p.id}
                  onClick={() => {
                    setSelectedProduct(p);
                    setVideoUrl(null);
                    setError(null);
                  }}
                  className={`relative shrink-0 h-28 w-20 rounded-xl overflow-hidden transition-all ${
                    selectedProduct?.id === p.id
                      ? "ring-2 ring-foreground scale-105"
                      : "opacity-70 hover:opacity-100"
                  }`}
                >
                  {p.image_url && (
                    <Image
                      src={p.image_url}
                      alt={p.name}
                      fill
                      className="object-cover"
                      sizes="80px"
                    />
                  )}
                </button>
              ))}
            </div>
          </div>

        </div>
      </div>
    </main>
  );
}
